package com.facturastock.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

internal val FacturaStockLightColors = lightColorScheme(
    primary = Color(0xFF365C9D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDCE7FF),
    onPrimaryContainer = Color(0xFF102A56),
    secondary = Color(0xFF596273),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE1E6F0),
    onSecondaryContainer = Color(0xFF242D3D),
    tertiary = Color(0xFF8D4F23),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDCC2),
    onTertiaryContainer = Color(0xFF321200),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF8F9FD),
    onBackground = Color(0xFF191C23),
    surface = Color(0xFFF8F9FD),
    onSurface = Color(0xFF191C23),
    surfaceDim = Color(0xFFD9DCE5),
    surfaceBright = Color(0xFFF8F9FD),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F3F8),
    surfaceContainer = Color(0xFFECEEF4),
    surfaceContainerHigh = Color(0xFFE5E7EE),
    surfaceContainerHighest = Color(0xFFDDE0E8),
    surfaceVariant = Color(0xFFE1E4EC),
    onSurfaceVariant = Color(0xFF44474F),
    outline = Color(0xFF74777F),
    outlineVariant = Color(0xFFC4C7D0),
    inverseSurface = Color(0xFF2E3038),
    inverseOnSurface = Color(0xFFF1F0F8),
    inversePrimary = Color(0xFFAFC6FF),
    surfaceTint = Color(0xFF365C9D),
    scrim = Color(0xFF000000),
)

internal val FacturaStockDarkColors = darkColorScheme(
    primary = Color(0xFFAEC6FF),
    onPrimary = Color(0xFF002E69),
    primaryContainer = Color(0xFF26477D),
    onPrimaryContainer = Color(0xFFD9E6FF),
    secondary = Color(0xFFC1C6D2),
    onSecondary = Color(0xFF2B313D),
    secondaryContainer = Color(0xFF3C4350),
    onSecondaryContainer = Color(0xFFE0E6F2),
    tertiary = Color(0xFFFFB77F),
    onTertiary = Color(0xFF502400),
    tertiaryContainer = Color(0xFF71380F),
    onTertiaryContainer = Color(0xFFFFDCC2),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF101218),
    onBackground = Color(0xFFE4E6EE),
    surface = Color(0xFF101218),
    onSurface = Color(0xFFE4E6EE),
    surfaceDim = Color(0xFF101218),
    surfaceBright = Color(0xFF363940),
    surfaceContainerLowest = Color(0xFF0B0D12),
    surfaceContainerLow = Color(0xFF171920),
    surfaceContainer = Color(0xFF1C1E26),
    surfaceContainerHigh = Color(0xFF262832),
    surfaceContainerHighest = Color(0xFF30323C),
    surfaceVariant = Color(0xFF444650),
    onSurfaceVariant = Color(0xFFC5C6D0),
    outline = Color(0xFF8E9099),
    outlineVariant = Color(0xFF454751),
    inverseSurface = Color(0xFFE4E6EE),
    inverseOnSurface = Color(0xFF2E3038),
    inversePrimary = Color(0xFF365C9D),
    surfaceTint = Color(0xFFAEC6FF),
    scrim = Color(0xFF000000),
)

@Immutable
data class FacturaStockSemanticColors(
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val info: Color,
    val onInfo: Color,
    val infoContainer: Color,
    val onInfoContainer: Color,
)

internal val LightSemanticColors = FacturaStockSemanticColors(
    success = Color(0xFF216577),
    onSuccess = Color(0xFFFFFFFF),
    successContainer = Color(0xFFD2EEF5),
    onSuccessContainer = Color(0xFF002028),
    warning = Color(0xFF765A00),
    onWarning = Color(0xFFFFFFFF),
    warningContainer = Color(0xFFFFE08A),
    onWarningContainer = Color(0xFF251A00),
    info = Color(0xFF5656A3),
    onInfo = Color(0xFFFFFFFF),
    infoContainer = Color(0xFFE4E0FF),
    onInfoContainer = Color(0xFF1B164F),
)

internal val DarkSemanticColors = FacturaStockSemanticColors(
    success = Color(0xFF9AD5E3),
    onSuccess = Color(0xFF003641),
    successContainer = Color(0xFF174E5A),
    onSuccessContainer = Color(0xFFC4F0FA),
    warning = Color(0xFFF0C94F),
    onWarning = Color(0xFF3E2E00),
    warningContainer = Color(0xFF584300),
    onWarningContainer = Color(0xFFFFE08A),
    info = Color(0xFFC5C1FF),
    onInfo = Color(0xFF2D286F),
    infoContainer = Color(0xFF423D83),
    onInfoContainer = Color(0xFFE4E0FF),
)
