package com.facturastock.app.data.ocr

/**
 * Puente PowerShell hacia el OCR integrado de Windows 10/11 (`Windows.Media.Ocr`).
 *
 * Se escribe en la caché privada y se ejecuta con Windows PowerShell 5.1 (`powershell.exe`):
 * solo esa edición (sobre .NET Framework) puede proyectar tipos WinRT con la sintaxis
 * `[Tipo, Ensamblado, ContentType = WindowsRuntime]`; PowerShell 7 (`pwsh`) no.
 *
 * El script se mantiene en ASCII puro: Windows PowerShell 5.1 lee un `.ps1` sin BOM con la
 * página de códigos ANSI del sistema, así que cualquier tilde en un comentario podría romperlo.
 * El JSON de salida también es ASCII (todo carácter no ASCII va como `\uXXXX`), de modo que no
 * dependemos de la codificación de consola ni de `ConvertTo-Json` (que en 5.1 tiene rarezas con
 * arreglos de un elemento y con la profundidad).
 *
 * Contrato (mantener sincronizado con [WindowsOcrJson] y [PowerShellWindowsOcrEngine]):
 * - `-RequestPath`: archivo UTF-8 con una ruta absoluta de imagen por línea, en orden de página.
 * - `-OutputPath`: archivo JSON escrito solo si todo salió bien.
 * - Códigos de salida: ver [WindowsOcrScript.EXIT_OK] y siguientes.
 * - Nunca se escribe texto reconocido en stdout/stderr (solo el tipo de la excepción).
 */
internal object WindowsOcrScript {
    /** Cambia el nombre cuando cambie el contenido para no reutilizar una copia vieja. */
    const val FILE_NAME = "facturastock-windows-ocr-v1.ps1"

    const val EXIT_OK = 0
    const val EXIT_BAD_REQUEST = 2
    const val EXIT_NO_OCR_LANGUAGE = 3
    const val EXIT_WINRT_UNAVAILABLE = 4
    const val EXIT_RECOGNITION_FAILED = 5

    val CONTENT: String = $$"""
# FacturaStock - bridge to the built-in Windows 10/11 OCR engine (Windows.Media.Ocr).
# Generated by the application; do not edit (it is rewritten on every OCR run).
#
# Usage:
#   powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File <this.ps1>
#       -RequestPath <request.txt> -OutputPath <result.json>
#
# request.txt : UTF-8, one absolute image path per line, in page order.
# result.json : written only on success, pure ASCII JSON:
#   {"pages":[{"index":0,"width":W,"height":H,"angle":A|null,
#              "lines":[{"text":"...","words":[{"text":"...","x":X,"y":Y,"w":W,"h":H}]}]}]}
#   width/height = pixel size of the bitmap actually handed to the engine (after EXIF
#   orientation and an optional downscale to OcrEngine.MaxImageDimension). Word rectangles
#   use that same pixel space, origin at the top-left corner. "angle" is OcrResult.TextAngle
#   (clockwise degrees) or null when the engine did not detect it.
#
# Exit codes: 0 ok | 2 bad request | 3 no OCR language installed |
#             4 WinRT OCR API unavailable | 5 decode/recognition failure.
# Recognized text is never written to stdout/stderr; only exception type names are.

param(
    [Parameter(Mandatory = $true)][string]$RequestPath,
    [Parameter(Mandatory = $true)][string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[System.Threading.Thread]::CurrentThread.CurrentCulture = [System.Globalization.CultureInfo]::InvariantCulture
$Invariant = [System.Globalization.CultureInfo]::InvariantCulture

function Stop-Ocr([int]$Code, [string]$Reason) {
    [Console]::Error.WriteLine($Reason)
    exit $Code
}

# ---------------------------------------------------------------------------------------------
# 1) Load the WinRT projections. This only works in Windows PowerShell 5.1 on Windows 10+.
# ---------------------------------------------------------------------------------------------
try {
    Add-Type -AssemblyName System.Runtime.WindowsRuntime
    $null = [Windows.Storage.StorageFile, Windows.Storage, ContentType = WindowsRuntime]
    $null = [Windows.Storage.FileAccessMode, Windows.Storage, ContentType = WindowsRuntime]
    $null = [Windows.Storage.Streams.IRandomAccessStream, Windows.Storage.Streams, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.BitmapDecoder, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.BitmapTransform, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.BitmapPixelFormat, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.BitmapAlphaMode, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.BitmapInterpolationMode, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.ExifOrientationMode, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.ColorManagementMode, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Graphics.Imaging.SoftwareBitmap, Windows.Graphics, ContentType = WindowsRuntime]
    $null = [Windows.Media.Ocr.OcrEngine, Windows.Foundation, ContentType = WindowsRuntime]
    $null = [Windows.Media.Ocr.OcrResult, Windows.Foundation, ContentType = WindowsRuntime]
    $null = [Windows.Globalization.Language, Windows.Foundation, ContentType = WindowsRuntime]
} catch {
    Stop-Ocr 4 ('winrt-unavailable: ' + $_.Exception.GetType().FullName)
}

# Standard trick to await an IAsyncOperation<T> from PowerShell 5.1: pick the generic
# System.WindowsRuntimeSystemExtensions.AsTask<T>(IAsyncOperation<T>) overload by reflection,
# close it over T and block on the resulting .NET Task.
$AsTaskGeneric = [System.WindowsRuntimeSystemExtensions].GetMethods() | Where-Object {
    $_.Name -eq 'AsTask' -and
    $_.IsGenericMethodDefinition -and
    $_.GetParameters().Count -eq 1 -and
    $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1'
} | Select-Object -First 1
if ($null -eq $AsTaskGeneric) {
    Stop-Ocr 4 'winrt-unavailable: AsTask overload not found'
}

function Wait-WinRt($Operation, [Type]$ResultType) {
    $task = $AsTaskGeneric.MakeGenericMethod($ResultType).Invoke($null, @($Operation))
    $null = $task.Wait(-1)
    return $task.Result
}

# ---------------------------------------------------------------------------------------------
# 2) Create the engine: the user's profile languages first, then any Spanish recognizer,
#    then whatever OCR language happens to be installed.
# ---------------------------------------------------------------------------------------------
$Engine = $null
try {
    $Engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromUserProfileLanguages()
} catch {
    $Engine = $null
}
if ($null -eq $Engine) {
    try {
        $spanish = [Windows.Globalization.Language]::new('es')
        if ([Windows.Media.Ocr.OcrEngine]::IsLanguageSupported($spanish)) {
            $Engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromLanguage($spanish)
        }
    } catch {
        $Engine = $null
    }
}
if ($null -eq $Engine) {
    try {
        $available = @([Windows.Media.Ocr.OcrEngine]::AvailableRecognizerLanguages)
        $preferred = @($available | Where-Object { $_.LanguageTag -like 'es*' }) + $available
        foreach ($language in $preferred) {
            if ($null -eq $language) { continue }
            $Engine = [Windows.Media.Ocr.OcrEngine]::TryCreateFromLanguage($language)
            if ($null -ne $Engine) { break }
        }
    } catch {
        $Engine = $null
    }
}
if ($null -eq $Engine) {
    Stop-Ocr 3 'no-ocr-language'
}

# ---------------------------------------------------------------------------------------------
# 3) Hand-written JSON (ASCII only, invariant culture, explicit nulls).
# ---------------------------------------------------------------------------------------------
function ConvertTo-JsonText([string]$Value) {
    if ($null -eq $Value) { return 'null' }
    $builder = New-Object System.Text.StringBuilder ($Value.Length + 2)
    $null = $builder.Append('"')
    foreach ($ch in $Value.ToCharArray()) {
        $code = [int]$ch
        if ($ch -ceq '"') {
            $null = $builder.Append('\"')
        } elseif ($ch -ceq '\') {
            $null = $builder.Append('\\')
        } elseif ($code -lt 0x20 -or $code -gt 0x7E) {
            $null = $builder.Append('\u').Append($code.ToString('x4', $Invariant))
        } else {
            $null = $builder.Append($ch)
        }
    }
    $null = $builder.Append('"')
    return $builder.ToString()
}

function ConvertTo-JsonNumber($Value) {
    if ($null -eq $Value) { return 'null' }
    $number = [double]$Value
    if ([double]::IsNaN($number) -or [double]::IsInfinity($number)) { return 'null' }
    return ([Math]::Round($number, 2)).ToString('R', $Invariant)
}

# ---------------------------------------------------------------------------------------------
# 4) Recognize every page in order.
# ---------------------------------------------------------------------------------------------
if (-not (Test-Path -LiteralPath $RequestPath -PathType Leaf)) {
    Stop-Ocr 2 'request-missing'
}
$ImagePaths = @([System.IO.File]::ReadAllLines($RequestPath, [System.Text.Encoding]::UTF8) |
    Where-Object { $_.Trim().Length -gt 0 })
if ($ImagePaths.Count -eq 0) {
    Stop-Ocr 2 'request-empty'
}

$MaxDimension = [double][Windows.Media.Ocr.OcrEngine]::MaxImageDimension
$Json = New-Object System.Text.StringBuilder
$null = $Json.Append('{"pages":[')

for ($index = 0; $index -lt $ImagePaths.Count; $index++) {
    $stream = $null
    $bitmap = $null
    try {
        $file = Wait-WinRt ([Windows.Storage.StorageFile]::GetFileFromPathAsync($ImagePaths[$index])) ([Windows.Storage.StorageFile])
        $stream = Wait-WinRt ($file.OpenAsync([Windows.Storage.FileAccessMode]::Read)) ([Windows.Storage.Streams.IRandomAccessStream])
        $decoder = Wait-WinRt ([Windows.Graphics.Imaging.BitmapDecoder]::CreateAsync($stream)) ([Windows.Graphics.Imaging.BitmapDecoder])

        # The engine rejects bitmaps larger than MaxImageDimension on either side: scale the
        # whole image down uniformly (the application maps coordinates back using width/height).
        $transform = [Windows.Graphics.Imaging.BitmapTransform]::new()
        $largest = [Math]::Max([double]$decoder.PixelWidth, [double]$decoder.PixelHeight)
        if ($MaxDimension -gt 0 -and $largest -gt $MaxDimension) {
            $scale = $MaxDimension / $largest
            $transform.ScaledWidth = [uint32][Math]::Max(1, [Math]::Floor([double]$decoder.PixelWidth * $scale))
            $transform.ScaledHeight = [uint32][Math]::Max(1, [Math]::Floor([double]$decoder.PixelHeight * $scale))
            $transform.InterpolationMode = [Windows.Graphics.Imaging.BitmapInterpolationMode]::Fant
        }
        # Bgra8 is accepted by every OcrEngine version; EXIF orientation is applied so the text
        # is upright exactly as the prepared JPEG is displayed.
        $pixelFormat = [Windows.Graphics.Imaging.BitmapPixelFormat]::Bgra8
        $alphaMode = [Windows.Graphics.Imaging.BitmapAlphaMode]::Premultiplied
        $orientation = [Windows.Graphics.Imaging.ExifOrientationMode]::RespectExifOrientation
        $colorMode = [Windows.Graphics.Imaging.ColorManagementMode]::DoNotColorManage
        $bitmapOperation = $decoder.GetSoftwareBitmapAsync($pixelFormat, $alphaMode, $transform, $orientation, $colorMode)
        $bitmap = Wait-WinRt $bitmapOperation ([Windows.Graphics.Imaging.SoftwareBitmap])

        $result = Wait-WinRt ($Engine.RecognizeAsync($bitmap)) ([Windows.Media.Ocr.OcrResult])

        if ($index -gt 0) { $null = $Json.Append(',') }
        $null = $Json.Append('{"index":').Append($index.ToString($Invariant))
        $null = $Json.Append(',"width":').Append(([int]$bitmap.PixelWidth).ToString($Invariant))
        $null = $Json.Append(',"height":').Append(([int]$bitmap.PixelHeight).ToString($Invariant))
        $null = $Json.Append(',"angle":').Append((ConvertTo-JsonNumber $result.TextAngle))
        $null = $Json.Append(',"lines":[')
        $firstLine = $true
        foreach ($line in $result.Lines) {
            if (-not $firstLine) { $null = $Json.Append(',') }
            $firstLine = $false
            $null = $Json.Append('{"text":').Append((ConvertTo-JsonText ([string]$line.Text)))
            $null = $Json.Append(',"words":[')
            $firstWord = $true
            foreach ($word in $line.Words) {
                if (-not $firstWord) { $null = $Json.Append(',') }
                $firstWord = $false
                $rect = $word.BoundingRect
                $null = $Json.Append('{"text":').Append((ConvertTo-JsonText ([string]$word.Text)))
                $null = $Json.Append(',"x":').Append((ConvertTo-JsonNumber $rect.X))
                $null = $Json.Append(',"y":').Append((ConvertTo-JsonNumber $rect.Y))
                $null = $Json.Append(',"w":').Append((ConvertTo-JsonNumber $rect.Width))
                $null = $Json.Append(',"h":').Append((ConvertTo-JsonNumber $rect.Height))
                $null = $Json.Append('}')
            }
            $null = $Json.Append(']}')
        }
        $null = $Json.Append(']}')
    } catch {
        $failure = $_.Exception
        while ($null -ne $failure.InnerException) { $failure = $failure.InnerException }
        Stop-Ocr 5 ('page ' + $index + ': ' + $failure.GetType().FullName)
    } finally {
        if ($null -ne $bitmap) { try { $bitmap.Dispose() } catch { } }
        if ($null -ne $stream) { try { $stream.Dispose() } catch { } }
    }
}

$null = $Json.Append(']}')
try {
    [System.IO.File]::WriteAllText($OutputPath, $Json.ToString(), (New-Object System.Text.UTF8Encoding $false))
} catch {
    Stop-Ocr 5 ('output: ' + $_.Exception.GetType().FullName)
}
exit 0
""".trimStart()
}
